### ISSUE TITLE
Sign Up Issue: An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by tguadalupe** [tguadalupe/UVI-Dining#2]
**Try to input campus location info to campus table. However, I came across this error:**

MySqlException: Cannot add or update a child row: a foreign key constraint fails (`uvi_dining`.`admins`, CONSTRAINT `admins_ibfk_1` FOREIGN KEY (`campus_id`) REFERENCES `campus` (`campus_id`))

**Comment by PinkDots** [comment]
I wonder , maybe we need a different sql query.

**Comment by tguadalupe** [comment]
I was wondering the same thing. 
Here's what I currently have in the LogValidator.cs Model:

```
 cmd.CommandText = "INSERT INTO campus(campus_id,campus_loc) values (@campus_id,@campus_loc)";
            cmd.Parameters.AddWithValue("@campus_id", campus_id);
            cmd.Parameters.AddWithValue("@campus_loc", campus_loc);

            //var cmd1 = Conn.CreateCommand() as MySqlCommand;
            cmd.CommandText = "INSERT INTO admins(FName,LName,Email,Password,user_Status,campus_id) values(@FName,@LName,@Email,@Password,@user_Status,@campus_id)";
            cmd.Parameters.AddWithValue("@FName", FName);
            cmd.Parameters.AddWithValue("@LName", LName);
            cmd.Parameters.AddWithValue("@Email", Email);
            cmd.Parameters.AddWithValue("@Password", Password);
            cmd.Parameters.AddWithValue("@user_Status", user_Status);
```

**Comment by PinkDots** [comment]
ohh okay. maybe a join?

**Comment by tguadalupe** [comment]
I don't think there's a join for insert however, there's an insert into select which I'm going to look more into it. 
https://www.w3schools.com/sql/sql_insert_into_select.asp

**Comment by tguadalupe** [comment]
Alright, we don't need an insert into select XD. So apparently in the SQL script Campus table, it was not populated with STT and STX which is why it was giving me that error. 

**For SQL Script:**
`INSERT INTO campus(campus_loc) values('STT'),('STX');`

I'm going to update the SQL Script as well as the file I updated.

**Comment by tguadalupe** [comment]
Issue solved! Yay
