### ISSUE TITLE
issue with foods page

### ISSUE THREAD

**Issue by PinkDots** [tguadalupe/UVI-Dining#6]
styling food pages causes the program to not work. 

campus id error

**Comment by tguadalupe** [comment]
Can you paste the code to the area that might cause the issue? We can debug it live together on blackboard collaborate.

**Comment by PinkDots** [comment]
Yes this is the code

 <br id="greenbarheight"> </br>

    <div id="greenbar"></div>

    <div class="nav">
        <ul>
            <li> <a href="/Project/Index">Home</a> </li>
            <li> <a href="/Project/Menu">Menu</a> </li>
            <li> <a href="/Project/Contact">Contact</a> </li>
            <li> <a href="/Project/aboutus">About Us</a> </li>

        </ul>
    </div>

    <br id="greenbarheight2"> </br>

    <div id="greenbar2"></div>

    <br id="greenbarheight3"> </br>

    <div id="greenbar3"></div>

    <p id="breakpoint"> </p>


    
     <br />
    <br />
      <p id="breakpoint"> </p>

**Comment by PinkDots** [comment]
body {
    margin: 0;
    background:rgb(250, 250, 250);
}


div.header {
    position: absolute;
    top: 10px;
    left: 9px;
}

.logo {
    float: left;
    height: 110px;
    width: 150px;
}



#greenbar {
    margin: -36px auto;
    background: #f4ca41;
    border: 1px solid #f4ca41;
    height: 40px;
    padding-left:20px;
}


/*---- top navigation bar */

.nav{
    height:52px;
    background-color:42f4bf;
    margin-top:-30px;
    padding-left:160px;
    
}

.nav ul{
list-style:none;
}

.nav ul li a{
    float:left;
    text-decoration:none;
    font-family:Helvetica;
    color:white;
    padding:0px 40px;
    text-align:center;
    line-height:52px;
    height:52px;
    font-size: 18px;
}

.nav ul li a:hover{
    background-color:white;
    color:aqua;
    border-radius:8px;
}


.nav ul li a.active{
    background-color:white;
    border-radius:8px;
    color:aqua;
}

/* bottom navigation bar */

div.navi1 {
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color:#f4ca41;
    margin-top:20px;
   
}

    .navi1 a {
        overflow: hidden;
        float: left;
        display:block;
        color:white;
        padding: 10px;
        font-size: 18px;
        
        
    }

        .navi1 a:hover {
            Opacity: 0.7;
        }








#greenbar2 {
    width: 100%;
    margin: -36px auto;
    background: lightgrey;
    border: 10 solid lightgray;
    height: 1px;
}


#greenbar3 {
    width: 100%;
    margin: 10px auto;
    background: lightgrey;
    border: 10 solid lightgray;
    height: 1.4px;
}






#breakpoint{

    
    margin-bottom:37.6%;
}

**Comment by tguadalupe** [comment]
It seems to be the breakpoint that's causing the issue. I notice you added two paragraph calling the breakpoint from the css file. If you remove the breakpoint that is above `<p id="breakpoint"> </p>` the program will stop crying and it will work again. 

It could also be beucase you are trying to space the same area which might conflit with the stuff you have under the other breakpoint which is odd. However, the goodnew is it's working now :sunglasses:  :smile_cat:

**Comment by PinkDots** [comment]
Oh, great.  It's working, thanks.
